name: Selenium Tests

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytest webdriver-manager pandas

      - name: Run forgot password tests
        run: pytest test_forgetPasswordTest1_2155.py

      - name: Run login tests
        run: pytest test_Wordpresslogin1_2155.py

      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: screenshots/*.png

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.csv
